spring:
  application:
    name: book-service
  
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./data/bookdb
#    username: sa
#    password: 
    
  datasource:
    url: jdbc:postgresql://localhost:5433/SpringBoot
    username: postgres
    password: jboss
    driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  security:
    user:
      name: admin
      password: secret123
    oauth2:
      client:
        registration:
          pricing-client:
            client-id: book-service
            client-secret: book-secret
            authorization-grant-type: client_credentials
            scope: internal
          provider:
            sas:
              token-uri: http://auth-server:7001/oauth2/token

  kafka:
    enabled: false
    bootstrap-servers:  # leave empty or comment out
      admin:
      fail-fast: false

pricing:
  service:
    url: http://localhost:8082


server:
  port: 8081
  address: 0.0.0.0

  error:
    path: /error2

sonar:
  jdbc:
    url: jdbc:postgresql://localhost:5432/sonar
    username: sonar
    password: sonar

management:
  endpoints:
    web:
      exposure:
        include: health,info,threaddump,mappings,metrics,prometheus
  endpoint:
    threaddump:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

logging:
  file:
    path: logs/ 
    name: logs/application.log 

## in production, you would typically use environment variables
# or a secrets manager to store sensitive information like the JWT secret key. 
# For example, you could set the JWT secret as an environment variable and reference it here:
## Azure → Key Vault
## in docker "docker run -e JWT_SECRET=very-long-random-key my-app"
## in linux/WSL export JWT_SECRET=very-long-random-key
## in powershell setx JWT_SECRET "very-long-random-key" and access it as jwt.secret=${JWT_SECRET} 
jwt:
  secret: veryverysecuresecretkey1234567890  # set as an environment variable
